name: tests-products

on:
  pull_request:
    paths:
      - "products/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd products && npm install && npm run test:ci
